Repository FC-DEV-FinalProject/FinalProject_5RE5_BE, pull requests merged in 2024-11, with the labels that each got.

#26 [feat] TtsAudioFile Repository 추가
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsAudioFile.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsAudiofile.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsSentence.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsSentenceAudio.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/repository/TtsAudioFileRepository.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsAudioFileRepositoryTest.java
Labels: Feature

#31 [Fix] : 오디오 파일 시그니처가 `00000000`로 변환 되는 오류 수정
  src/main/java/com/oreo/finalproject_5re5_be/audio/AudioExtensionConverter.java
Labels: bugFix

#42 [feat] .gitignore 파일 수정
  .gitignore
Labels: Feature

#45 [chore] auto assign을 위한 설정
  .github/CODEOWNERS
Labels: setting

#74 [feature] VcService, AudioFileInfo 기능 추가
  build.gradle
  src/main/java/com/oreo/finalproject_5re5_be/audio/dto/response/AudioFileInfo.java
  src/main/java/com/oreo/finalproject_5re5_be/audio/service/AudioInfo.java
  src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/README.md
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcAudioRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcSeqRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcSrcRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/request/VcTextRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/response/AudioGetResponse.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/response/README.md
  src/main/java/com/oreo/finalproject_5re5_be/vc/dto/response/VcResponse.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/Vc.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcErrorLog.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcRequestLog.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultFile.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcResultLog.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcSrcFile.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcText.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/entity/VcTrgFile.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/repository/VcRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/repository/VcResultFileRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/repository/VcSrcFileRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/repository/VcTargetFileRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/repository/VcTextRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/README.md
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/audio/service/AudioInfoTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsProgressStatusRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsSentenceRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/vc/repository/VcSrcFileRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImplTest.java
Labels: test, Feature

#90 [Refactor] : 해당 인터 페이스에서 오디오 리샘플링을 수행하는 로직 분리
  src/main/java/com/oreo/finalproject_5re5_be/audio/Concatenator.java
  src/test/java/com/oreo/finalproject_5re5_be/audio/ConcatenatorTest.java
Labels: refactor

#111 [feat] tts 행 수정 기능
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsSentence.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/TtsControllerTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceTest.java
Labels: Feature

#120 [Feature] project controller 추가
  src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java
  src/main/java/com/oreo/finalproject_5re5_be/project/controller/README.md
  src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImpl.java
Labels: Feature

#134 [feat] 단일 행 조회 기능
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/TtsControllerTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceTest.java
Labels: test, Feature

#162 [CI] CD 구축 수정
  .github/workflows/cdscript.yml
Labels: deploy

#167 [refactor] tts 서비스 및 컨트롤러 테스트 코드 분리
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/TtsControllerTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestGetSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestGetSentenceList.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestMakeTts.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestRegisterSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestUpdateSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestAddSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestGetSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestGetSentenceList.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestUpdateSentence.java
Labels: refactor

#171 [Fix] 보이스, 스타일 엔티티와 응답 DTO 수정
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/StyleDto.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/VoiceDto.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/ServerCode.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/Style.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/Voice.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/StyleControllerTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/VoiceControllerTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/SampleAudioRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/StyleRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsProcessHistoryRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsProgressStatusRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/TtsSentenceRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepositoryFindTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/repository/VoiceRepositoryTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/StyleServiceTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/TtsMakeServiceTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/VoiceServiceTest.java
Labels: bugFix

#179 [chore] : Swagger 어노테이션 추가
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/LanguageController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/StyleController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/VoiceController.java
Labels: docs

#195 [feat] Concat BGM 기능 추가
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/bgm/BgmProcessor.java
  src/main/java/com/oreo/finalproject_5re5_be/global/component/audio/AudioFormats.java
Labels: Feature

#203 [feat] TTS 문장 comparator 구현
  src/main/java/com/oreo/finalproject_5re5_be/global/exception/InValidValueException.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchInfo.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/SentenceInfo.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/exception/DuplicatedSentenceException.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/exception/InValidRequestException.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/exception/ProjectMismatchException.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/util/TtsSentenceComparator.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestPatchSentenceOrder.java
Labels: Feature

#204 [feature] Concat Bgm 컨트롤러 추가
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatResultController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatWithBgmController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/dto/ConcatResponseDto.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/dto/RowInfoDto.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/SelectedConcatRowRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/entity/AudioFormat.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/entity/ConcatResult.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/repository/AudioFormatRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioFileService.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioFormatService.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatResultService.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/bgm/BgmProcessor.java
  src/main/java/com/oreo/finalproject_5re5_be/global/component/audio/AudioResample.java
Labels: Feature

#205 [fix] TTS ERD 반영
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/response/SentenceInfo.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/entity/TtsSentence.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestAddSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestUpdateSentence.java
Labels: bugFix

#206 [fix] project vaild fix
  src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java
  src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
  src/main/java/com/oreo/finalproject_5re5_be/project/exception/projectNotMemberException.java
  src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectService.java
  src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImplTest.java
Labels: bugFix

#209 [feat] VCController 회원Session 값으로 회원확인
  src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/exception/VcNotMemberException.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcService.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java
Labels: Feature

#218 [refactor] project 조회 tts, vc, concat, 생성날짜 추가
  src/main/java/com/oreo/finalproject_5re5_be/concat/repository/README.md
  src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java
  src/main/java/com/oreo/finalproject_5re5_be/project/dto/response/ProjectResponse.java
  src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
  src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImpl.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/repository/TtsSentenceRepository.java
  src/test/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImplTest.java
Labels: Feature

#219 [fix] VC SRC 행 생성 오류
  src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java
Labels: bugFix

#220 [fix] 스케줄러 작동 9시로 변경
  .github/workflows/schedule-pr.yml
Labels: bugFix, deploy

#216 [Feat] TTS 생성 실패 처리 추가
  src/main/java/com/oreo/finalproject_5re5_be/global/component/ByteArrayMultipartFile.java
  src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/exception/SaveTtsMakeResultException.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/SaveTtsMakeResultService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsMakeService.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/SaveTtsMakeResultTest.java
Labels: Feature

#222 [CI] MAIN 푸쉬
  .github/workflows/schedule-pr.yml
  src/main/java/com/oreo/finalproject_5re5_be/concat/repository/README.md
  src/main/java/com/oreo/finalproject_5re5_be/global/component/ByteArrayMultipartFile.java
  src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
  src/main/java/com/oreo/finalproject_5re5_be/member/config/LoginAuthenticationFailureHandler.java
  src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfig.java
  src/main/java/com/oreo/finalproject_5re5_be/project/controller/ProjectController.java
  src/main/java/com/oreo/finalproject_5re5_be/project/dto/response/ProjectResponse.java
  src/main/java/com/oreo/finalproject_5re5_be/project/entity/Project.java
  src/main/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImpl.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/controller/TtsController.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/exception/SaveTtsMakeResultException.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/repository/TtsSentenceRepository.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/SaveTtsMakeResultService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsMakeService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceService.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/controller/VcController.java
  src/main/java/com/oreo/finalproject_5re5_be/vc/service/VcServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/member/config/MemberSecurityConfigTest.java
  src/test/java/com/oreo/finalproject_5re5_be/project/service/ProjectServiceImplTest.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestGetSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestGetSentenceList.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestMakeTts.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestRegisterSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/controller/ttsController/TestUpdateSentence.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/SaveTtsMakeResultTest.java
Labels: deploy

#226 [feat/refactor] bgm 컨트롤러 리팩토링, concat 관련 엔드포인트마다 check메서드 추가
  src/.idea/.gitignore
  src/.idea/vcs.xml
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/AudioFileController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatMaterialController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatResultController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatRowController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatTabController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatWithBgmController.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/dto/request/ConcatUpdateRequestDto.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/AudioStreamService.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/ConcatResultService.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/MaterialAudioService.java
  src/main/java/com/oreo/finalproject_5re5_be/concat/service/bgm/BgmProcessor.java
  src/main/java/com/oreo/finalproject_5re5_be/global/component/S3Service.java
  src/test/java/com/oreo/finalproject_5re5_be/concat/controller/ConcatMaterialControllerTest.java
  src/test/java/com/oreo/finalproject_5re5_be/concat/service/ConcatTabServiceTest.java
Labels: Feature, refactor

#229 [fix] swagger 에서 batchSave 엔드포인트의 request body 가 의도하지 않은 출력이 나오는 이슈
  src/main/java/com/oreo/finalproject_5re5_be/tts/dto/request/TtsSentenceBatchRequest.java
  src/main/java/com/oreo/finalproject_5re5_be/tts/service/TtsSentenceServiceImpl.java
  src/test/java/com/oreo/finalproject_5re5_be/tts/service/ttsSentenceService/TestBatchSave.java
Labels: bugFix

#245 [fix] MemberConfig http 제거
  src/main/java/com/oreo/finalproject_5re5_be/member/config/MemberConfig.java
Labels: bugFix
